name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libudunits2-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            gdal-bin \
            proj-bin

      - name: Install spatial dependencies first
        run: |
          Rscript -e '
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("terra", "sp", "raster"), dependencies = TRUE)
          '

      - name: Install basic R packages
        run: |
          Rscript -e '
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("shiny", "shinydashboard", "sf", "leaflet"))
          '

      - name: Install remaining R dependencies
        run: |
          Rscript -e '
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c(
            "wordcloud2",
            "dplyr",
            "DT",
            "readxl",
            "writexl",
            "ggplot2",
            "tidyr",
            "rsconnect"
          ))
          '

      - name: Verify installations
        run: |
          Rscript -e '
          packages <- c("shiny", "shinydashboard", "leaflet", "sf", "dplyr")
          missing <- packages[!packages %in% installed.packages()[,"Package"]]
          if(length(missing) > 0) {
            stop("Missing packages: ", paste(missing, collapse=", "))
          }
          print("All required packages are installed")
          '
        
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e '
          library(rsconnect)
          rsconnect::setAccountInfo(
            name="${{ secrets.SHINYAPPS_NAME }}",
            token="${{ secrets.SHINYAPPS_TOKEN }}",
            secret="${{ secrets.SHINYAPPS_SECRET }}"
          )
          rsconnect::deployApp(
            appDir = ".",
            appName = "happiness-analysis",
            appTitle = "Happiness Analysis",
            launch.browser = FALSE,
            forceUpdate = TRUE
          )
          '
