on:
  push:
    branches:
      - main

name: Deploy Happiness App to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: 💎 Deploy to shinyapps.io
        uses: qwert666/shinyapps-actions@main
        env:
          SHINY_USERNAME: 'morgancab'  # Remplacez par votre nom d'utilisateur shinyapps.io
          SHINY_TOKEN: ${{ secrets.TOKEN }}
          SHINY_SECRET: ${{ secrets.SECRET }}
          APP_NAME: 'happiness-analysis'    # Nom de votre application
          APP_DIR: ''                       # Laissez vide si votre app est à la racine
